### ISSUE TITLE
Guess the secret formula

### ISSUE THREAD

**Issue by NikolajBjorner** [microsoft/z3guide#110]
Given a set of "secret formulas", have user guess the formula by submitting candidate formulas.
Output is one of the following:

- Done
- Model satisfying secret formula negation of user formula
- Model satisfying user formula, negation of secret formula

**Comment by NikolajBjorner** [comment]
Example

Secret formula: x is even.

(declare-const x Int)
(assert (= (mod x 2) 0))


The user is given the declarations.

```
(declare-const x Int)
```

They don't see the secret formula.

They enter some formula

```
(assert (> x 0))
```

The tool creates two SMT queries (in secret):

```
(declare-const x Int)
(assert (= (mod x 2) 0))
(assert (not (> x 0)))
(check-sat)
(get-model)
```


```
(declare-const x Int)
(assert (not (= (mod x 2) 0)))
(assert (> x 0))
(check-sat)
(get-model)
```

If the queries are sat then the user sees the output (models) with an explanation that says this is a value that satisfies the secret formula but not yours or the other way around.

**Comment by pelikhan** [comment]
is there a generic way to negate the model provided by the user (without known anything about the STM format)

`(assert (> x 0))` -> `not(assert (> x 0))` ???

**Comment by NikolajBjorner** [comment]
There isn't textually.
We can use the API to parse the formula and then extract the formula and manipulate it.

const s1 = new Z3.Solver()
const s2 = new Z3.Solver()
s1.from_string(user_input)
s2.from_string(secret_input)
const not_user = Z3.Not(Z3.And(s1.assertions()))
const not_secret = Z3.Not(Z3.And(s2.assertions()))
s2.add(not_user)
s1.add(not_secret)
const secret_not_user = await s2.check()
const user_not_secret = await s1.check()
if (secret_not_user == "sat")
    // say   s2.model().sexpr() satisfies secret but not user formula
if (user_not_secret == "sat")
   // etc

**Comment by NikolajBjorner** [comment]
if you use text, you have to account for potential multiple asserts :-(. So not a simple regex

**Comment by pelikhan** [comment]
your snippet looks great

**Comment by NikolajBjorner** [comment]
We would just store a few "secret" formulas in plaintext to start with as SMTLIB format.

**Comment by rlisahuang** [comment]
Seems like `from_string` doesn't exist on `Context` type in the JS bindings.
