### ISSUE TITLE
Funky cursor position

### ISSUE THREAD

**Issue by rlisahuang** [microsoft/z3guide#113]
The cursor position is somewhat nondeterministic when switching to a new line. It flicks around and has bad user experience. It gets exacerbated when user interacts with the website without a mouse (keyboard tabbing interaction). 

It may be related to the internal bug of `use-editable`. We might be able to force reset cursor position on every keydown if the key is Enter.

API: https://github.com/FormidableLabs/use-editable

**Comment by pelikhan** [comment]
Eventually it looks like we'll have to switch to something like Ace or Monaco.
