### ISSUE TITLE
Updating to z3-solver version 4.12.0 breaks when evaluating js

### ISSUE THREAD

**Issue by NikolajBjorner** [microsoft/z3guide#147]
repro steps

```
cd website
yarn update z3-solver --latest
yarn clear
yarn build
```

After a little:

```
Error: z3-js runtime error: 09a64c920ec19d9abca6b64bcfd471dd9d8e2a7f, z3-failed, const x = Z3.Int.const('x');
Z3.solve(Z3.And(x.ge(10), x.le(9)));, Error: main.ts (-5,82): Cannot find module 'z3-solver'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?
main.ts (-2,45): Type 'any' has no signatures for which the type argument list is applicable.
Error: z3-js runtime error: 36105bbd16a2093ae1f5531ea6d7961e3d38955d, z3-failed, const solver = new Z3.Solver();
const sort = Z3.Int.sort();
const x = Z3.Int.const('x');
const y = Z3.Int.const('y');
const g = Z3.Function.declare('g', sort, sort);
const conjecture = Z3.Implies(x.eq(y), g.call(g.call(x)).eq(g.call(y)));
solver.add(Z3.Not(conjecture));
await solver.check()
solver.model(), Error: main.ts (-5,82): Cannot find module 'z3-solver'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?
main.ts (-2,45): Type 'any' has no signatures for which the type argument list is applicable.
[ERROR] Client bundle compiled with errors therefore further build is impossible.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

The relevant file would then be eval-z3.ts.

```
// - takes a snippet like `let x = Z3.foo(); await Z3.check(x);`
// - puts it in a context where `Z3` is defined and `await` works
// - modifies the last expression to be a return statement, like `let x = Z3.foo(); return await Z3.check(x);`
// - typechecks the result
// - and strips types
// successful output looks like `"use strict"; module.exports = (async () => { ... })();`
export function compileZ3JS(src: string) {
  let imports = `
  import type { init as initT, Model, Solver, BitVecNum, AstVector, Arith } from 'z3-solver';
  declare let init: typeof initT;
  declare let { Context, setParam }: Awaited<ReturnType<typeof init>>;
  declare let Z3: ReturnType<typeof Context<'main'>>;
  `;
  let wrapped = `
${imports}
export = (async () => {
${src}
```

**Comment by NikolajBjorner** [comment]
The main change since 4.11.0 that is relevant could be the commit,
https://github.com/Z3Prover/z3/commit/f175fcbb54c3bd18de96cc9b889e110cf4234809
On a frist read it appears to just add some new sub-classes without affecting previous classes.

I am currently not clear how to read the error message 
main.ts (-2,45): Type 'any' has no signatures for which the type argument list is applicable.
as the line position -2 should relate to some of the auto-generated code.

**Comment by bakkot** [comment]
> I am currently not clear how to read the error message
> main.ts (-2,45): Type 'any' has no signatures for which the type argument list is applicable.

From the error message, the problem is more likely to be the previous line:

> Error: main.ts (-5,82): Cannot find module 'z3-solver'.

which indicates that it isn't able to find `z3-solver` during the build process. I don't see the same error when I try the same process locally (except with `yarn upgrade z3-solver --latest` in place of `yarn update z3-solver --latest`; `yarn update` is not a thing).

The subsequent "Type 'any' has no signatures" error is probably a consequence of not being able to find the module with the types, and doesn't really mean anything on its own (just that it can't compile without having access to the types).

**Comment by walnutwaldo** [comment]
Like the comment above, I also was able to get Z3 version 4.12.0 working locally, though I had to change my node version to `v16.19.0` (the version used by the GitHub build hooks) to fix some other obscure errors of my own. @NikolajBjorner perhaps you could try changing your node version if it isn't `16.19.0` already?

**Comment by NikolajBjorner** [comment]
I guess node exposes something then.

This is on my laptop:
C:\z3guide\website>node -v
v18.13.0

Thanks for the inputs. I will then check on my desktop when I get back home (or push to a branch and check the build machines).

**Comment by rlisahuang** [comment]
I tried building it locally with node `v16.15.1`, which got me a different runtime error regarding type mismatch. However, after trying `v16.9.0` as what @walnutwaldo suggested, the build was successful. So I can confirm that node was causing the issue.

**Comment by NikolajBjorner** [comment]
update: I was able to get further with codespaces, but not with my Windows machines. This suggests the issue to be external (or a configuration setting that resolves differently on platforms).

**Comment by NikolajBjorner** [comment]
@rlisahuang - could it be that we also have to update z3-solver version in package.json?
https://github.com/microsoft/z3guide/blob/main/website/package.json

**Comment by NikolajBjorner** [comment]
It is resolved to: package.json has to be synchronized with upgrade.sh
