### ISSUE TITLE
TotalLinearOrder -> LinearOrder

### ISSUE THREAD

**Issue by LeventErkok** [microsoft/z3guide#154]
This isn't in the guide itself, but rather in the paper:

https://theory.stanford.edu/~nikolaj/programmingz3.html#sec-special-relations

The text refer to `TotalLinearOrder`. However, I believe in the implementation this is simply called `LinearOrder`. (So the example in the text does not load actually.)

The guide has the correct name.

**Comment by NikolajBjorner** [comment]
will be fixed on https://z3prover.github.io/papers/programmingz3.html
