### ISSUE TITLE
z3 fail -> build fail

### ISSUE THREAD

**Issue by pelikhan** [microsoft/z3guide#23]
- [x] Ensure that if a snippet cannot be processed during build, the entire github action fails as well (and no deployment is generated).
- [x] Ensure that logging is good enough to trace which snippet needs to be investigated. Try to generate an formatted error message in the output so that the github action automatically highlights where the problem is

**Comment by rlisahuang** [comment]
Snippet cannot be processed => something with syntax error?

`eval_smtlib2_string` guarantees to return a string, meaning the error messages will be part of `stdout` if an error occurs. I think we *want* the syntax errors for debugging/changing the snippets?

**Comment by rlisahuang** [comment]
All errors are now rendered in the front-end, so examining the errors by hand on the website is feasible

**Comment by NikolajBjorner** [comment]
I guess the expectation is that I fix the errors unless it is obvious.
There are other errors that don't require me in the critical loop: 
- I wonder what happend to the "Arithmetic" section. It looks incomplete. It has "Division" but no other subsections.
- I ended up fixing various low hanging issues. For example, _ should be escaped in markdown mode.
So overall a lot of quality control left at this point, not considering the new material on Sequences I have been adding today.

**Comment by rlisahuang** [comment]
Incomplete "Arithmetic" section: looks like you are missing `.md` suffixes for some files

**Comment by bakkot** [comment]
> meaning the error messages will be part of `stdout` if an error occurs

Note that you can call `Z3.get_error_code` right after calling `Z3.eval_smtlib2_string` to determine if there was an error without needing to parse the output, as in `console.log('had error?', Z3.get_error_code(ctx) !== Z3_error_code.Z3_OK)`. You'll need to import `Z3_error_code` in the same place you import `init`.

There's also `Z3.get_error_msg` but unfortunately it will include the rest of the output from `eval_smtlib2_string`. I haven't checked if this is a bug in the wasm frontend or if that's just what Z3 itself does.

**Comment by NikolajBjorner** [comment]
in smtlib2 mode (where it interprets a string) the errors are printed to the output string. There can be multiple errors.
This is what is relevant to the SMTLIB2 interpreter mode.
Those errors are not accessible from the error code or message.

**Comment by NikolajBjorner** [comment]
close?
