### ISSUE TITLE
use remark pluging logger

### ISSUE THREAD

**Issue by pelikhan** [microsoft/z3guide#25]
The second argumen of visit should be a logger; we should use that in order to get proper logging in the builds

**Comment by pelikhan** [comment]
Also add support for github annotations format

**Comment by rlisahuang** [comment]
ref: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-a-warning-message
from: https://github.com/microsoft/rise4fun/commit/663a786f39de026fab57465edd8e4e8dbde441ec#commitcomment-77467560
(just linking everything together for my own reference)

**Comment by rlisahuang** [comment]
API for `visit`: `(tree: Node, test_node: string, visitor: Function, reverse?: boolean)`

Doesn't seem to have an argument for a logger.

Is our current logging mechanism enough? If so we can close this one.
