### ISSUE TITLE
landing page inconsistent

### ISSUE THREAD

**Issue by pelikhan** [microsoft/z3guide#26]
![image](https://user-images.githubusercontent.com/4175913/176921204-d507bf22-0bf0-472b-8db7-9d7a47559d99.png)

- [x] big title at start should probably have some other content
- [x] learn z3 at bottom section is somewhat misleading as it takes the user to another web site. suggestion: remove

**Comment by ayanamonr** [comment]
Changed Learn Z3 to more z3 and removed tutorial link. If flat out deleting is still preferable it's an easy fix.
