### ISSUE TITLE
toc titles inconsistent

### ISSUE THREAD

**Issue by pelikhan** [microsoft/z3guide#27]
![image](https://user-images.githubusercontent.com/4175913/176923676-2d4419b8-79f7-42d2-976c-64e34466760d.png)

**Comment by NikolajBjorner** [comment]
Somehow the order of these items is random and not following the order in the navbar meta-data.

**Comment by NikolajBjorner** [comment]
It must be related to how to lay out the side bar: https://docusaurus.io/docs/sidebar

**Comment by rlisahuang** [comment]
> Somehow the order of these items is random and not following the order in the navbar meta-data.

You would need to prefix the directories of these titles (showing up in the nav bar) with numbers to specify their order. E.g., `01 - Intro` shows up before `03 - Advanced Topics`.

**Comment by NikolajBjorner** [comment]
AFAIK, it uses the directory name for the side-bar, so then '01 - Intro' would show up, not "Introduction". 
OTOH, if the directory only has a single file, it uses the title from the file.. For example, Playground

**Comment by rlisahuang** [comment]
So I did some experiments: adding numeric prefixes to directory names only affects the order of the content, not their names on the page. I believe docusaurus did some post-processing to remove the numerals from the content eventually rendered. So I believe it is safe to go ahead with adding numeric prefixes such as `01 - Fixedpoints`.
