### ISSUE TITLE
top level organization issues

### ISSUE THREAD

**Issue by NikolajBjorner** [microsoft/z3guide#30]
![image](https://user-images.githubusercontent.com/3085284/176985692-b691809e-08e2-4944-883c-77243d607592.png)

There are several issues with the top-level organization.

- The top-level organization shows z3 topics on the main landing page. The z3 topics should (eventually?) only show up when selecting the z3 tutorial (reflecting that rise4fun is more than z3 even though current activities are z3 centric).
- When selecting the z3 tutorial the page is undefined. What is the right link? Where should it be added?
- The side bar shows z3 sections in an indeterminate order. The order in the upper task bar is according to a json file, but the order in the left side bar is neither logical, nor alphabetical.

**Comment by pelikhan** [comment]
> The top-level organization shows z3 topics on the main landing page. The z3 topics should (eventually?) only show up when selecting the z3 tutorial (reflecting that rise4fun is more than z3 even though current activities are z3 centric).

There's a bit of a confusion here. This web site should be all about Z3; but built in the "rise4fun" template. Eventually we'll have hosted content for each tool stored in separate locations.

rise4fun really refers to a project template that will allow to create an interactive tool web site easily

**Comment by NikolajBjorner** [comment]
I am still confused because the web site is called https://microsoft.github.io/rise4fun

It contains the button to get to the z3 tutorial, but the rest of the landing page is very specific to z3.
![image](https://user-images.githubusercontent.com/3085284/177015093-6f214076-dbb8-4301-8115-271dd3383c53.png)

For example, it contains the header with "Strategies" "Fixedpoints".
It also contains the footer with references to z3.

Should we just put the entire page into https://microsoft.github.io/z3guide?

**Comment by pelikhan** [comment]
We need rename the repo to z3guide AND update some config flags in the docusaurus.config.js

**Comment by NikolajBjorner** [comment]
You make the decisions, I don't have all context anyhow. But who executes? I think it would be for @rlisahuang to rename repo.

**Comment by rlisahuang** [comment]
The one-repo-one-tool concept sounds reasonable. On top of everything, we would need a separate landing page for all rise4fun tools, where the current z3 tutorial will be linked from there.

**Comment by rlisahuang** [comment]
I will do the renaming after the two interviews today. A bunch of changes are needed and I want to avoid breaking anything before we show the preview version to our interviewees.

**Comment by pelikhan** [comment]
We can rename the repository to update rise4fun to z3guide or something... Yes it's not rise4fun, it's all about z3 right now.

The landing page is most stale and has not been updated at all.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
