### ISSUE TITLE
Mismatched output from z3-wasm vs. z3 executable

### ISSUE THREAD

**Issue by rlisahuang** [microsoft/z3guide#32]
Several code snippets from our tutorial would not work in [the web interface cited above](https://virb3.github.io/z3-wasm/). According to @NikolajBjorner z3-wasm does produce different outputs than the z3 executables.

Code snippet example:
```
(set-option :print-success true) 
(set-option :produce-unsat-cores true) ; enable generation of unsat cores
(set-option :produce-models true) ; enable model generation
(set-option :produce-proofs true) ; enable proof generation
(declare-const x Int)
(set-option :produce-proofs false) ; error, cannot change this option after a declaration or assertion
(echo "before reset")
(reset)
(set-option :produce-proofs false) ; ok
```

Moving the conversation from #19 .

The possible solutions we face:
1. Remove tutorial materials that contain such problems;
2. Coordinate with @NikolajBjorner and @bakkot on a wasm build that produces consistent outputs.

**Comment by NikolajBjorner** [comment]
We test against the npmjs release. In the meanwhile, I have updated the z3 code on github to address these issues. The next release (soon) should show different behavior.

**Comment by NikolajBjorner** [comment]
we have no-build and ignore-error markings
