### ISSUE TITLE
Use z3 version 4.9.1

### ISSUE THREAD

**Issue by NikolajBjorner** [microsoft/z3guide#36]
There is a new release of z3 out today.
It doesn't seem to get picked up by the build.
It has some npm version dependencies as well that have changed.
With this release we should be able to remove some of the no-build tags.

**Comment by rlisahuang** [comment]
Let me look into it

**Comment by NikolajBjorner** [comment]
Note, this may be blocking at the moment
https://github.com/Z3Prover/z3/pull/6139

**Comment by rlisahuang** [comment]
So we roll back to 4.8.7 until notified?

**Comment by rlisahuang** [comment]
I actually don't think that it is a good idea to automate updating z3. A broken / incompatible version can break our code. For any dependency including z3-solver, we would need to test if a newer version is compatible with our codebase before upgrading it.

**Comment by rlisahuang** [comment]
The update is simple as well. Running `yarn install <package_name>` locally / in codespaces (not through github workflows) will update `package.json` and `yarn.lock` accordingly, which will be later picked up by github actions.

**Comment by rlisahuang** [comment]
I just enforced z3-solver 4.8.17 on main. Ping me when the update is ready and I'll test and update manually.

**Comment by NikolajBjorner** [comment]
4.9.1 is out now, npmjs should be updated soon. Let's see if this one works.

**Comment by rlisahuang** [comment]
4.9.1 merged to main now. I added an `ignore-errors` flag to the code snippet
```
(simplify (_char 100000000))
```
per your request.
