### ISSUE TITLE
Katex Math 

### ISSUE THREAD

**Issue by ayanamonr** [microsoft/z3guide#4]
- [ ] enable katex to render the math necessary

**Comment by rlisahuang** [comment]
[This guide from docusaurus](https://docusaurus.io/docs/markdown-features/math-equations) seems to be straightforward. @ayanamonr let me know after you have incorporated content involving math equations so I could enable and test the configuration.

**Comment by rlisahuang** [comment]
@NikolajBjorner Would you expect to have the display of math formula supported for the current guide?

**Comment by pelikhan** [comment]
Yes we want to enable KaTeX. Docusaurus has a guide I think.
________________________________

**Comment by NikolajBjorner** [comment]
The page on lambdas now uses simple $ $ environments. 
The GitHub renderer supports these, but the guide not yet.

https://microsoft.github.io/z3guide/docs/logic/Lambdas/

**Comment by rlisahuang** [comment]
I added katex config. Looks like you would need two `$` signs to use katex. See examples [here](https://docusaurus.io/docs/markdown-features/math-equations#blocks).

**Comment by rlisahuang** [comment]
Config error fixed, katex should be up now.
