### ISSUE TITLE
Landing Page Polishing

### ISSUE THREAD

**Issue by rlisahuang** [microsoft/z3guide#49]
Currently thinking about the design from https://infinum.github.io/eightshift-docs/, minus the sections below intro. So just one big background, a big title, some text description, and two buttons that get you to Tutorial and Playground, respectively.

It should be able to be done through pure CSS.

TODOs:
- [ ] background pic?
- [ ] landing page redesign
- [ ] theme color? thinking about blu-ish due to the current Z3 logo
- [ ] @NikolajBjorner Z3 logo in SVG/PNG?

**Comment by NikolajBjorner** [comment]
@ayanamonr - should we create an updated z3 logo?

**Comment by pelikhan** [comment]
Test on mobile...
