### ISSUE TITLE
New Logo for Z3

### ISSUE THREAD

**Issue by ayanamonr** [microsoft/z3guide#50]
create a new logo for the site and for potential "merch" and such

https://www.figma.com/file/8DIxJUBYNPj9AqOxifgoPQ/Z3-Designs?node-id=0%3A1

**Comment by NikolajBjorner** [comment]
On merch: how about a cusyom jacdac wearble?

**Comment by NikolajBjorner** [comment]
Asking Teddy, Michal, Peli, Tom

**Comment by ayanamonr** [comment]
![image](https://user-images.githubusercontent.com/25496296/182681326-3323f626-567c-4432-b822-bcdaae98b2d9.png)
