### ISSUE TITLE
Onboarding documentation

### ISSUE THREAD

**Issue by rlisahuang** [microsoft/z3guide#55]
- [ ] a. Forking this website to extend / customize the existing z3 guide and host on the user's own github pages; 
- [ ] b. Forking the tutorial template to customize an online tutorial for a custom language

**Comment by pelikhan** [comment]
This may be a bit early. We need to think more about make this reusable, configurable.

**Comment by rlisahuang** [comment]
Makes sense. Just thinking about people who might fork this repo to extend/create their own content. Also for user B, in case they are interested in further customizing the code blocks.

**Comment by pelikhan** [comment]
Definitely an important and tricky question: how do you architect rise4fun as a reusable, updatable, configurable framework. 

Might be worth looking at other examples and see if there are patterns that have been successful (docusaurus is one example).

We definitely don't want people to fork z3guide, it's going to generate tons of half broken clones.
