### ISSUE TITLE
Configure Codespace + Onboarding

### ISSUE THREAD

**Issue by ayanamonr** [microsoft/z3guide#6]
- [x] make sure instructions for this step is clear for a user (subject b)
- [x] note: content in a subfolder 
- [x] make sure everything in codespace is installed on launch 
- [x] instruction on dev server launch should be clear
- [x]  !!! as we hear about what professors need edit

**Comment by rlisahuang** [comment]
@pelikhan I checked in some devcontainer files using templates provided by VSCode. I don't think Codespaces is enabled for this repo yet as the green `Code` button doesn't provide an option to start one. 

Would you mind: 
- [ ] Checking if the files I checked in make sense; and
- [ ] Enabling Codespaces / Testing that the config works?

**Comment by rlisahuang** [comment]
Close?

**Comment by ayanamonr** [comment]
I think so, I was able to follow all instructions on my personal computer
