### ISSUE TITLE
Main takeaways from the design interviews

### ISSUE THREAD

**Issue by rlisahuang** [microsoft/z3guide#78]
Interview progress: 1 done out of 4 scheduled

### Website
- [x] Rename Z3 `Documentation` to `Guide` -- the former indicates API stuff, whereas the latter implies that it is targeted for learning and there will be examples
    - Users don't realize that there are real examples within the guide. How to make the examples more discoverable? / How to make the fact that this guide entails real examples more explicit?

- [ ] "Edit this page" links you to the github page for the raw document, can be confusing to users and maybe should be removed
- [x] Playground should be editable at the first run? Now the interaction flow requires you to click Run to render the output first, before allowing you to edit, which may be counterintuitive

### Programming Experience
- [x] syntax highlighting
    - [x] More specifically, parentheses highlighting / matching is a MUST for the SMTLIB-based examples
- [x] Autocompletion for parentheses?
    - Could be confusing at times so I suggest let's wait and see
- [ ] Debugging support
    - [x] Line numbers -- for locating errors based on the error message, which includes line/col numbers
    - [ ] Highlighting -- emphasizing the line(s) that are buggy
- [x] Copy button
    - Already provided in the native editor on hover. Bring it back!
- [ ] ?Store programming progress in some way (e.g., cookies) so that you don't lose your progress when you refresh the page / close the window
    - [x] Reset button: in case you modified the content in the tutorial (i.e., not in the playground), you want to restore the original content
- [ ] ?"Save to file" button for the playground editor

**Comment by NikolajBjorner** [comment]
Instead of "Edit this page", why not call it "Improve this page"?
I think the link is good to have, just what it is called.
