### ISSUE TITLE
configure syntax highlighting

### ISSUE THREAD

**Issue by pelikhan** [microsoft/z3guide#82]
prism-react-renderer comes with only so many languages built in. This might explain why lisp is not working.

https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js

**Comment by pelikhan** [comment]
This is how we added C# support in jacdac -> https://github.com/microsoft/jacdac-docs/blob/main/src/components/CodeBlock.tsx#L21

**Comment by NikolajBjorner** [comment]
Parenthesis matching aid would help a lot for LISP. You never know when the parentheses are not matched. Maybe comes with a LISP highlighter.

**Comment by rlisahuang** [comment]
Look like the fix will only work for our native editor, not the `LiveEditor` we now rely on.
