### ISSUE TITLE
package.json scripts

### ISSUE THREAD

**Issue by pelikhan** [microsoft/z3guide#88]
Move .sh script logic to package.json script section; so that we can simply do `yarn ...`

IMO, it's ok to tell the user to first to `cd website`.

**Comment by rlisahuang** [comment]
The logic already exists:
- `yarn` for installing dependencies
- `yarn start` for client-side rendering with hot reloading (starting local dev server)
- `yarn clear` for clearing out cache
- `yarn build` for client- and server-side rendering if you want to inspect the output of the build
- `yarn serve` for serving the build output locally _without_ hot reloading
so if we tell them to `cd website` at first, then the scripts of `init.sh` and `run.sh` won't be necessary, except for `upgrade-z3.sh`. 

Should we go with this decision?

**Comment by pelikhan** [comment]
yes, get rid of the init/run.sh files. it's less stuff to maintain.

**Comment by pelikhan** [comment]
it's a bit dubious that we have a subfolder "website"; maybe a lot of this can be simplified by moving all the content of website down into the root folder (requires orchestration between all users of the repo)

**Comment by rlisahuang** [comment]
I thought that was an intentional architecture decision we made initially?

**Comment by pelikhan** [comment]
it does not make any sense really since we've put all the content under website anyway.
