### ISSUE TITLE
Move discussion button next to paste button

### ISSUE THREAD

**Issue by pelikhan** [microsoft/z3guide#93]
Same idea as it is visible when in the context of that snippet.

![image](https://user-images.githubusercontent.com/4175913/183774973-2a2156a5-393a-4b2b-904a-5aa7308ecb07.png)

**Comment by rlisahuang** [comment]
Fixed in https://github.com/microsoft/z3guide/pull/95/commits/466ec061499d033dc68b98e8ed003de5c192d719
